"""Persist original upload reservations and source ownership."""

import sqlalchemy as sa

from alembic import op

revision = "0045_original_upload_ownership"
down_revision = "0044_rag_index_write_fences"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "original_upload_attempts",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("asset_version_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("folder_id", sa.Uuid(), nullable=True),
        sa.Column("new_document", sa.Boolean(), nullable=False),
        sa.Column("store_id", sa.String(length=80), nullable=False),
        sa.Column("binding_id", sa.Uuid(), nullable=False),
        sa.Column("suffix", sa.String(length=8), nullable=False),
        sa.Column("generation", sa.BigInteger(), nullable=True),
        sa.Column("canonical_key", sa.String(length=700), nullable=False),
        sa.Column("temporary_key", sa.String(length=700), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("revision", sa.BigInteger(), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "((state = 'open' OR (state = 'abandoned' AND revision = 2)) AND size IS NULL "
            "AND sha256 IS NULL) OR ((state IN ('published','attached','discarding') OR (state = "
            "'abandoned' AND revision = 4)) AND size IS NOT NULL AND size >= 0 AND sha256 "
            "IS NOT NULL AND sha256 ~ '^[0-9a-f]{64}$')",
            name="ck_original_upload_content",
        ),
        sa.CheckConstraint(
            "(state = 'open' AND revision = 1) OR (state = 'published' AND revision = 2) OR"
            " (state = 'attached' AND revision = 3) OR (state = 'discarding' AND revision = 3) OR"
            " (state = 'abandoned' AND revision IN"
            " (2,4))",
            name="ck_original_upload_state_revision",
        ),
        sa.CheckConstraint(
            "canonical_key = workspace_id::text || '/' || document_id::text || '/' || "
            "replace(id::text, '-', '') || suffix",
            name="ck_original_upload_canonical",
        ),
        sa.CheckConstraint("store_id ~ '^[a-z][a-z0-9_]{0,79}$'", name="ck_original_upload_store"),
        sa.CheckConstraint(
            "suffix IN ('.pdf','.docx','.pptx','.xlsx','.txt','.md','.html','.htm')",
            name="ck_original_upload_suffix",
        ),
        sa.CheckConstraint(
            "temporary_key = workspace_id::text || '/' || document_id::text || '/.' || "
            "replace(id::text, '-', '') || '.upload.tmp'",
            name="ck_original_upload_temporary",
        ),
        sa.CheckConstraint(
            "(new_document AND generation IS NULL) OR (NOT new_document AND generation >= 1"
            " AND generation IS NOT NULL)",
            name="ck_original_upload_generation",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "id",
            "workspace_id",
            "document_id",
            "asset_version_id",
            name="uq_original_upload_source",
        ),
        sa.UniqueConstraint(
            "store_id", "binding_id", "canonical_key", name="uq_original_upload_canonical"
        ),
        sa.UniqueConstraint(
            "store_id", "binding_id", "temporary_key", name="uq_original_upload_temporary"
        ),
    )
    op.create_index(
        "ix_original_upload_document",
        "original_upload_attempts",
        ["workspace_id", "document_id"],
        unique=False,
    )
    op.create_index(
        "ix_original_upload_unattached",
        "original_upload_attempts",
        ["workspace_id", "state"],
        unique=False,
    )
    op.create_table(
        "original_file_resources",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("asset_version_id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("revision = 1", name="ck_original_resource_revision"),
        sa.ForeignKeyConstraint(
            ["document_id", "asset_version_id"],
            ["asset_versions.document_id", "asset_versions.id"],
            name="fk_original_resource_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["id", "workspace_id", "document_id", "asset_version_id"],
            [
                "original_upload_attempts.id",
                "original_upload_attempts.workspace_id",
                "original_upload_attempts.document_id",
                "original_upload_attempts.asset_version_id",
            ],
            name="fk_original_resource_attempt",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "document_id"],
            ["documents.workspace_id", "documents.id"],
            name="fk_original_resource_document",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_version_id", name="uq_original_resource_version"),
    )
    op.create_index(
        "ix_original_resource_document",
        "original_file_resources",
        ["workspace_id", "document_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("original_file_resources")
    op.drop_table("original_upload_attempts")
